service:
  name: vidalog-server

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'